### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by gabrielbodard** [SASDigitalHumanitiesTraining/3D#1]
Please leave a comment here telling us a bit about your project and/or your reason for learning 3D imaging and modelling—in lieu of a social gathering at the start of the summer school. You may also use this as an opportunity to try out some of the features of this forum/issuetracker, Markdown encoding, etc.

**Comment by thein13** [comment]
Hello, my name is Alex. My main research is on Roman Republican history, but I'm also involved in the Digital Augustan Rome project, and though it's 2D at the moment we're thinking of how to develop it in the future. My interest in the summer school is to learn SketchUp for teaching, to introduce different types of assessment in a class on Pompeii, but I can see photogrammetry has great potential for a Roman sculpture class, also for objects in the UCD Classical Museum, and developing outreach projects for 2nd-level schools.

**Comment by GeorgePrew** [comment]
Hello! I'm George and I am a third year PhD Archaeology student at the University of Glasgow. My research focuses on the performance of ancient funerary dress in early Iron Age Italy, for which I hope soon to be working with artists to reconstruct the sensory experience of early Iron Age funerals. This will ideally include 3D modelling of one or more graves, so I hope to get some ideas for starting this off during the school. Previously, I have used 3D models for teaching (replacing handling sessions for the last year of Zoom teaching), and I have undertaken structured light scanning on ancient pots for a research project in early 2020, so I am also excited to learn more about photogrammetry.

**Comment by KaterinaVolioti** [comment]
Hi, my name is *Katerina, and I am **not** a techi. I teach Classical art at Roehampton. When not teaching I study Greek vases, see [here] (https://roehampton-online.academia.edu/KaterinaVolioti). With this course I hope to embed digital humanities in two undergrad modules. I look forward to learning from you all.

**Comment by KaterinaVolioti** [comment]
Hi, my name is *Katerina* and I am **not** a techi. I teach Classical Art at Roehampton and I am doing this course to embed digital humanities in undergraduate teaching. I look forward to learning from you all.

**Comment by LindaStoessel** [comment]
Hi, my name is Linda. I am a PhD student in Classical Archaeology at the University of Tuebingen, Germany. In my research I focus mainly on **Roman Architecture**. My thesis deals with the aesthetics of economic architecture in Rome in the late Republic and early Imperial period. For this I analyze buildings, individual architectural elements and the urbanistics of Rome. In field projects, during my MA thesis and through collegues I learned about the potential of photogrammetry for the documentation and presentation of architecture. In general and in case it might become useful in the course of my work, I like to learn more about the production and the potential of 3D models.

**Comment by Al-scw** [comment]
Thanks again to you all for joining this summer school, I found it really engaging and was inspired by all your projects. My sketchfab account is [https://sketchfab.com/awalsh](url), and please feel free to drop me an email any time for questions or a chat.

**Comment by GeorgePrew** [comment]
Thank you and Gabby for hosting it! It was really fascinating, and so useful. I am much less help, but if anyone wants to keep in touch or discuss Iron Age corpse fashion, my sketchfab is [here](https://sketchfab.com/GeorgePrew), and my email address can be found [here](https://www.gla.ac.uk/pgrs/georgeprew/) - It would be great to see what everyone gets up to scanning and modelling!

**Comment by Lynchtosca** [comment]
Many thanks again for organising this Summer School, Gabby and Alicia! Here is [my Sketchfab](https://sketchfab.com/ToscaACLynch) and the [second model I produced yesterday](https://skfb.ly/ooCoT). You can find more information on my research and further contact details [on my Academia profile](https://oxford.academia.edu/ToscaLynch)!

**Comment by thein13** [comment]
Portrait bust uploaded to: https://sketchfab.com/thein
I haven't figured out how to search for people to follow...
