### ISSUE TITLE
Meshmixer functions

### ISSUE THREAD

**Issue by HansvanWees** [SASDigitalHumanitiesTraining/3D#10]
I have been playing around with Meshmixer, and am finding it hard.  Following the instructions in Valeria Vitale's 'Monster in your pocket', I have managed to splice three human heads on to a bunny rabbit.  So far so good.  But each element appears in a different colour, and I cannot work out how to unify them - or really to do anything with them at all...   I know that there are some instructions for each function under f1, but they have not helped.  When I left-click and drag the brush, nothing appears to happen except that a sort of orbit appears on the image, which does not seem to do anything further.  Any advice?  Or any chance of a further demonstration in the afternoon?
In the meantime, I am trying to generate a model from Dan Petts' photos, too, and picked the Lachish reliefs because I occasionally use these in teaching, but as it stands the dense-cloud generation stage still has 7.5 hours to run (and that for a low quality setting!), so it won't be ready for today's session.
By the way, I also tried generating something from the Troy photos I mentioned, but Metapshape could not align a single one of 30 photos of the stairs, so I had to give that up.  It's odd, though, because some of the pictures are nearly identical and one would think they are not that hard to relate...

**Comment by Al-scw** [comment]
Hi Hans, to combine the elements into one singular mesh, try holding SHIFT and selecting each one- a tool bar will appear and click COMBINE. Now you should have a singular mesh to work with. 
Sorry to hear the old Troy photos didn't work. There are a number of reasons they couldn't align, overlapping images being just one of them. It usually comes down to image quality and whether or not they were all taken with the same camera settings. Have you tried manually aligning them by using markers as tie points?

**Comment by HansvanWees** [comment]
Thanks, Alicia.  I have selected the whole object so that it is now all orange, but I see no 'combine' button anywhere, unfortunately...  
Happy to try manual alignment for the Troy photos, but as yet have not worked out how to do that.

**Comment by gabrielbodard** [comment]
I don't see a "Combine" option in Meshmixer either (nor can I see how to shift+select, but maybe that's a Mac difference?). I would expect **Select --> Edit --> Join** to do what we're looking for, but that just crashes on my Meshmixer. I may try upgrading, as I'm still using version 3.4…

**Comment by gabrielbodard** [comment]
(Can we move the "manually aligning historical photos" discussion into [ticket #5](https://github.com/SASDigitalHumanitiesTraining/3D/issues/5) please? Keeps things clearer…)

**Comment by HansvanWees** [comment]
Thanks, Gabby - sorry to raise multiple issues in a single comment.  I get the same result as you from 'Edit/Join' - 'fatal error' (and I'm on 3.3 because I could not get 3.5 to install).
