### ISSUE TITLE
Deterioration in uploading on Sketchfab?

### ISSUE THREAD

**Issue by HansvanWees** [SASDigitalHumanitiesTraining/3D#11]
So, after 10 hours of processing the model of the Lachish relief (or as it turns out just the least interesting bit of it!) was done on Metashape, and despite the low quality settings selected at every stage, it looked good: details all clearly visible when you zoom in. However, when I uploaded it on Sketchfab, it came out as the pointless blur you can see via this link.

https://sketchfab.com/3d-models/lachish-relief-side-panel-3d-91da56aeb54b4a4f814a3e08fc956bd9

The same deterioration occurred with my aryballos, which was done with medium quality settings, and very much better in Metashape than what you see on Sketchfab.  I was happy to accept the blame for poor photography then, but unless this is also the problem with Dan Petts's pix, I am beginning to think there is another problem or I am missing a trick.  Or is it simply that only the highest-quality settings produce something acceptable on Sketchfab?   Has anyone else had this problem?

**Comment by HansvanWees** [comment]
It looks like my problem is that I have uploaded an incomplete set of files or the wrong type of file(s).  I can try again with the original aryballos, where I do at least have the three types of file that are needed. With the siege of Lachish reliefs, however, I seem to have generated somehow a different set of things: a .dae file, a .jpeg and a 'metashape project' file.  I  uploaded the .dae; tried uploading the .jpg but was told Sketchfab cannot accept it.  The metashape project version is, I assume, the file that one uses in Metashape and is not for uploading on Sketchfab.  So (a), I don't understand why I did not generate the same set of files, and (b) I don't know how to generate and upload the whole set successfully.

**Comment by HansvanWees** [comment]
OK, so that was not the problem after all.  I tried again with the aryballos, all three files, and it looks exactly the same, i.e. an ugly blur, when it looks OK (so far as sharpness of details is concerned - I know that there is a lot else wrong with it!) in Metashape.

**Comment by Al-scw** [comment]
Hi Hans, they don't look too bad on Sketchfab, but maybe because I can't see the comparison shown on Metashape... did you try experimenting with the 3D setting tools on Sketchfab shown by Tom? the sharpness tool may make all the difference. 
In terms of file types, you could try exporting again as an OBJ and uploading that along with the MTL and JPG (you will probably have to compress them to a zip folder as they may be too big for the basic upload size on sketchfab).

**Comment by HansvanWees** [comment]
Thanks, Alicia, I have tried again with the small aryballos, not zipped admittedly, but the result was the same. When you say 'not too bad', do you mean you can see the details of the Assyrian reliefs?  What I see on Sketchfab is only just good enough to show that it is some kind of relief, with maybe a glimpse of a head or an arm occasionally but it is impossible to see what it represents, let alone zoom in on the fine details.  Basically, it looks like the version you get on Metashape before you apply the texture - which is why I thought it might have missed the texture file.


Hans van Wees
Grote Professor of Ancient History
History Department, University College London
Gower Street, London WC1E 6BT, UK
***@***.******@***.***> • office: 020 7679 3633


________________________________

**Comment by HansvanWees** [comment]
This time I sent the aryballos in a zipped file, and when uploading I got the following 'issues' warnings:
Material Lib [ "Aryballos ] is used but a matching file could not be found.
Material Lib [ Model.mtl" ] is used but a matching file could not be found.
Material [ Aryballos_Model ] is used but its declaration could not be found.
File [ Aryballos Model.jpg ] is present in the archive but seems unused.

**Comment by nebulousflynn** [comment]
Hello, Tom from Sketchfab here. 

It looks like the main issue here is missing / unassigned texture maps. There are a few ways to remedy this issue, I suggest you try these first:

1. Use the built in Metashape to Sketchfab uploader (File Menu > Upload Data... > Sketchfab)
2. Open the 3D Settings for each model and [upload and assign the textures manually](https://help.sketchfab.com/hc/en-us/articles/202600873-Materials-and-Textures#textures)

**Comment by HansvanWees** [comment]
Thanks, Tom.  I tried the direct upload from Metashape and got 'error: bad request'.   I 'll try the other option later.

**Comment by HansvanWees** [comment]
Sorry to be a pain, but I believe I have run through every menu I can see in my Sketchfab, but found nothing called 'Textures' or 'Albedo', either under 'Materials' or anywhere else.  I'm using a PC, if that makes a difference...

**Comment by HansvanWees** [comment]
Oh, wait, I've found 'Albedo' now, a few layers down...

**Comment by HansvanWees** [comment]
Great - the image is much sharper now.  There are other problems with it but perhaps I will find the solutions to those eventually.  Many thanks for your help.

**Comment by chattyplatty** [comment]
Hans - I find exactly the same with mine. The quality of my model in Sketchfab is just not as nuanced - so I am going to try Tom's suggestions too - thank you, Tom!
