### ISSUE TITLE
SketchUp general question

### ISSUE THREAD

**Issue by thein13** [SASDigitalHumanitiesTraining/3D#12]
Still in the early stages of working through the tutorials, but a couple of general questions:

- Is it broadly the case that you always start with something basic like a rectangle or a box, and then push/pull/distort into shape?
- Do you always start with the measurements, or do some people import a ground plan image and then draw up from that? And for the measurements you have to have a report, with dimensions given in the text, correct? As opposed to using a ruler with a ground plan and trying to calculate from the scale bar (which I can't see working).

- specific example: how would you create a colonnaded courtyard? One rectangle for the outer wall would work to start with, but what about the internal colonnade? Do you start with a wall, make openings, and then fashion the wall sections into columns and put a roof over the top?

Struggling a bit with how to turn basic principles into something more complex...

**Comment by gabrielbodard** [comment]
> * Is it broadly the case that you always start with something basic like a rectangle or a box, and then push/pull/distort into shape?

That's the basic way to model from scratch in Sketchup, yes. You can also make slightly more diverse primary shapes (circles, arcs, hand-drawn lines), but the principle is the same. Of course, you could also create a component in another 3D tool (e.g. by photogrammetry) and import that into Sketchup, and then build up from there—incorporating it in a larger structure, deforming and extending it, etc.

**Comment by gabrielbodard** [comment]
> * Do you always start with the measurements, or do some people import a ground plan image and then draw up from that? And for the measurements you have to have a report, with dimensions given in the text, correct? As opposed to using a ruler with a ground plan and trying to calculate from the scale bar (which I can't see working).

You can do it either way, yes. If you have detailed dimensions and measurements, either from the literature or compiled yourself from archaeological plans, architectural drawings, you own observation, or as you say extrapolation from a drawing with a scale, you can then write yourself up a detailed workflow as Valeria did in the handout we're using for practice, with dimensions of all elements.

The other method is, as you say, to import the ground plan as an image and lay it on a horizontal plane, and then use that as a guide to build your walls and other features. (Sadly the topography on the ground image will not cause your cursor to "snap to" the edges, so you'll have to model them a bit more freehand, but it will be a guideline at least.) I guess you would want to be careful to scale your ground plan against the scale of the environment, as well…

**Comment by gabrielbodard** [comment]
> * specific example: how would you create a colonnaded courtyard? One rectangle for the outer wall would work to start with, but what about the internal colonnade? Do you start with a wall, make openings, and then fashion the wall sections into columns and put a roof over the top?

For a colonnade I might be inclined to make the columns by drawing circles on the ground and extruding/pulling them upwards to the desired height (rather than try to cut them back from a rectangular wall), and then possibly texture them with an image file that gives the appearance of a decorated/fluted/etc column. You could also import a 3D model of the column and duplicate that a couple dozen times to make your colonnade, though—the individual columns would have lots of triangles/planes each to give them 3D geometry, and I wouldn't want to sculpt that myself! It depends how much detail you want. There are some columns in the 3D warehouse, e.g., but not every kind of ancient column, I'm sure.

I suspect @Al-scw will have more to add on both (or other) options, however.

**Comment by thein13** [comment]
Dear Gabby, thank you for the answers to my questions: I'd like to be able to learn to do something like the single Greek house model that Chiara distributed, and eventually to do two walls of the Macellum at Pompeii. One wall is well preserved with wall paintings, and we have textual descriptions of the other wall, and what I'd like to do is replicate the pattern from the West to the North wall, to figure out how many panels there were (as this affects the reading of the images). There are good photos of the West wall, and I'm sure there are a lot of older drawings/images of the North wall - maybe Valeria has advice on how to find all of them, I've found only a couple, almost certainly not all of them... BTW: the Pompeii forum has been mapped (properly, with a theodolite) by a project at Virginia, and it's online - do you think it would be possible (in theory) to cut/paste the ground plans, or would it have to be drawn from scratch?

P.S. to share images tomorrow do we need to set up SketchFab accounts, and does what we upload need to be published and tagged, or is there a way to share privately with the group?

**Comment by chattyplatty** [comment]
Reading this - doing the Macellum at Pompeii would be excellent!! What an excellent project to do!

**Comment by chattyplatty** [comment]
> > * specific example: how would you create a colonnaded courtyard? One rectangle for the outer wall would work to start with, but what about the internal colonnade? Do you start with a wall, make openings, and then fashion the wall sections into columns and put a roof over the top?
> 
> For a colonnade I might be inclined to make the columns by drawing circles on the ground and extruding/pulling them upwards to the desired height (rather than try to cut them back from a rectangular wall), and then possibly texture them with an image file that gives the appearance of a decorated/fluted/etc column. You could also import a 3D model of the column and duplicate that a couple dozen times to make your colonnade, though—the individual columns would have lots of triangles/planes each to give them 3D geometry, and I wouldn't want to sculpt that myself! It depends how much detail you want. There are some columns in the 3D warehouse, e.g., but not every kind of ancient column, I'm sure.
> 
> I suspect @Al-scw will have more to add on both (or other) options, however.

Hi Gabby and Alicia, I'd be interested to know with columns, do they always have to be perfect circles? Or can they be scalloped in Sketchfab, as they often are in ancient buildings?

**Comment by thein13** [comment]
> Reading this - doing the Macellum at Pompeii would be excellent!! What an excellent project to do!

Last time I was there I tried to visualise things in my mind by pacing things out....! P.S. one painting survives on the N wall, and there are textual descriptions of three more, and I want to do the measurements to see if it's three along the whole N wall, or just the initial section before the door half way along. All traces now lost, even of the stucco, and I couldn't get much out of the Naples model. Otherwise I suppose I need to dig to see if there are 19th drawing books (something I haven't done much with yet)

**Comment by Al-scw** [comment]
For fluted columns, what you could do is create a circle, then use the arc tool along the circle to make it concave, then extrude from there. I would then duplicate this a few times to create a colonnade.

**Comment by chattyplatty** [comment]
That makes sense - thank you for that Alicia!

**Comment by gabrielbodard** [comment]
@thein13 After your question above, I tried importing a ground plan (screenshot from the villa gardens article as a PNG) into a scaled rectangle in Sketchup Make, and have started drawing and extruding walls from there. It's slow work, but it seems to do the job. We can discuss more later if you like.

**Comment by gabrielbodard** [comment]
> For fluted columns, what you could do is create a circle, then use the arc tool along the circle to make it concave, then extrude from there. I would then duplicate this a few times to create a colonnade.

That was my first thought too, but given that columns are not usually uniform all the way up (they may taper, as well as having capitals and bases) or think I would go back to my initial response of trying to find a model made by someone else (or photogrammetry or similar) and importing it, if I wanted a really good shaped column.
