### ISSUE TITLE
Crediting question 

### ISSUE THREAD

**Issue by OrlyLewis** [SASDigitalHumanitiesTraining/3D#14]
Hi everyone, 

I wanted to raise a non-technological question for discussion here or during today's meeting, if there is time and inclination.

I was hoping to hear your thoughts about how to cite and credit 3D models in cases of collaboration with professional modelers, that is, they do the actual modelling but following your guidelines and through an iterative discussion with you, or perhaps even you and other colleagues/students. 
How would you refer to this in a paper, repository, sketchfab and other publication formats? How would you cite these models on your Orcid / CV?

In a forthcoming printed paper I have some 2D images prepared in collaboration though the paper is single-authored. I've included an explanation at the beginning of the paper about the process and those involved and under each figure I stated 'Image by with the name of the illustrator + my project's name. Does this sound right to you? 

But how about when publishing the actual images / models on a repository (or sketchfab for that matter)? 
I feel this should be similar to multi-authored publications. But in what order should the names appear? First the modeler? Any thoughts or experience on this?

Thanks in advance for any comments (and apologies for not being able to contribute anything to the Sketchup issues - I am still working out the preliminary stages of it all... ).

Many thanks in advance!
Orly

**Comment by LindaStoessel** [comment]
An important question! Your citation oft he printed 2D images sound ricght to me. In a printed paper of a project we are about to publish a 2D orthofoto extracted from a photogrammetry. We named all involved (four people, among them photographer/geodesist and modeler) in alphabetical order. I guess when publishing models on a repository I would also handle it similar to a multi-authored publication

**Comment by OrlyLewis** [comment]
Thanks Linda! That's good to know.
In this paper I can't change the authorship of the entire paper; it's part of a volume which began a while back and I only thought of adding images very recently. So it's even more important for me to publish the images as standalone outputs (with annotations); also, the publisher has only agreed to include some of the images we created. The limitations of the traditional medium... 
Thanks again.

**Comment by gabrielbodard** [comment]
An excellent example of the reason we need to think about academic credit as well as legal intellectual property; by our norms and standards, someone who creates something for us as "work for hire" and therefore doesn't hold the IP in the object, nevertheless should be credited for their work, as co-authorship, or in the image caption, or similar. Bear in mind also that different disciplines have different expectations of what co-authorship and order of named authors means, so while alphabetical order might work for us, a computer scientist looking at it might make specific interpretations of what the first author vs the last author did…

The [Contributor Roles Taxonomy](https://casrai.org/credit/) helps a bit with disentangling this in the digital realm, but we still have to get used to reading author lists on a CV vel sim, where there's not really room for this sort of explanation.

If someone creates something based on my detailed instructions, which are based on my research and experience and opinions, then which is most important on the credit list: my intellectual direction or their expertise? (Linda's choice of alphabetical order suggests they have equal weight, which sounds fair to me.)

**Comment by OrlyLewis** [comment]
Good points! The difference in disciplines troubles me too, since some of the people involved in our anatomical models are from the life sciences and as you say, they have a very strict order and different from the humanities. 
The taxonomy link you shared is very useful - often in applications one is asked to explain their particular role in each joint publication. This taxonomy can help in formulating things in a more unified way and I think even include it in brief under each publication item, at least in some CV versions.
