### ISSUE TITLE
SketchUp scaling imported objects

### ISSUE THREAD

**Issue by thein13** [SASDigitalHumanitiesTraining/3D#15]
I'm still only half way through the first exercise:

- having imported the Venus de Milo I looked up the original on Google and found it was 2 m tall. I first tried to adjust the height in the blue boxes, using the box at the bottom right of the screen, the one we used to change rectangle sizes, and it seemed to work, but then there was a glitch and suddenly the statue was twice as tall as the building, without me changing any of the measurements. Obviously I'd done something wrong.

- my solution was to use the tape measure, to create a guide line and then to drag the statue to the same height. It looks ok, but I'm sure it's not 100% accurate. Is there a better way of doing it?

- also: is there a way of clicking a statue onto its base? Or do you just have to move it manually roughly into position and hope it looks ok.

- P.S. even though only half way through, looks nice to see the paintings through the columns. One question: the 30 cm gap on all sides of the images, is that to account for the way the frescoes were removed from the walls, i.e. an archaeological decision, or is it a SketchUp thing, like pulling images off the walls?

**Comment by gabrielbodard** [comment]
> * P.S. even though only half way through, looks nice to see the paintings through the columns. One question: the 30 cm gap on all sides of the images, is that to account for the way the frescoes were removed from the walls, i.e. an archaeological decision, or is it a SketchUp thing, like pulling images off the walls?

My understanding is that it's the former, yes—there was a section of the fresco lost as a result of the removal process, so what is in the museum is smaller than the originals, and the gaps represents that. (I can check with Valeria if we want to be sure.) It would be useful to document that decision, wouldn't it…

**Comment by gabrielbodard** [comment]
> * also: is there a way of clicking a statue onto its base? Or do you just have to move it manually roughly into position and hope it looks ok.

I think (but haven't checked) that if you drag the statue from one of its bottom corners, then it ought to "snap to" an edge of the base you're trying to place it on. (Or if that fails, you could draw a guideline, and snap it to that?)

**Comment by thein13** [comment]
> > * also: is there a way of clicking a statue onto its base? Or do you just have to move it manually roughly into position and hope it looks ok.
> 
> I think (but haven't checked) that if you drag the statue from one of its bottom corners, then it ought to "snap to" an edge of the base you're trying to place it on. (Or if that fails, you could draw a guideline, and snap it to that?)

Thank you, it's sort of working - tried to centre the statue, added guidelines, but couldn't snap to them, ended up doing it by sight. Hard to know if the base is even supposed to be centred with the Venus de Milo, though, given the shape of the body and its centre of mass

Still wondering about setting the statue height: I'd have thought that's one thing that could be done to the millimetre.

**Comment by thein13** [comment]
Imported my own photogrammetry image, but:

1. it's blue: how do I get the normal texture, i.e. to look like a statue?
2. it's on an angle: is that because I saved it wrong in Metashape, or is it because I haven't done anything in Meshmixer?
3. I can't get it to move onto a base - the move function seems to have got stuck with the rotate function, and at one point I found myself locked onto the walls of the building, distorting them out of shape at the same time as the statue was moving.

**Comment by Al-scw** [comment]
> Imported my own photogrammetry image, but:
> 
> 1. it's blue: how do I get the normal texture, i.e. to look like a statue?
> 2. it's on an angle: is that because I saved it wrong in Metashape, or is it because I haven't done anything in Meshmixer?
> 3. I can't get it to move onto a base - the move function seems to have got stuck with the rotate function, and at one point I found myself locked onto the walls of the building, distorting them out of shape at the same time as the statue was moving.

Check out this issue the other issue on "Sketchup...!" as some of these questions have been discussed there

**Comment by gabrielbodard** [comment]
> Still wondering about setting the statue height: I'd have thought that's one thing that could be done to the millimetre.

Yes, I'm still trying to see if there's a way to do this (other than setting two guidelines exactly the right distance apart and then snapping to them). Currently googling for Sketchup help. :) The issue seems to be that you can only manually set the exact dimensions when you create a shape, not after the fact (perhaps because it would have all sorts of knock-on effects?). I'll let you know if I have any joy…

**Comment by Al-scw** [comment]
> 2\. it's on an angle: is that because I saved it wrong in Metashape, or is it because I haven't done anything in Meshmixer?

It may be because the orientation wasn't fixed in Meshmixer, but you can always change it in Sketchup

**Comment by gabrielbodard** [comment]
Re scaling an object to an exact dimension: this video seems to show how to do what we want: https://youtu.be/KsM7u2d6JI0 (I haven't tested it yet, but it looks good.)

**Comment by thein13** [comment]
> > Imported my own photogrammetry image, but:
> > 
> > 1. it's blue: how do I get the normal texture, i.e. to look like a statue?
> > 2. it's on an angle: is that because I saved it wrong in Metashape, or is it because I haven't done anything in Meshmixer?
> > 3. I can't get it to move onto a base - the move function seems to have got stuck with the rotate function, and at one point I found myself locked onto the walls of the building, distorting them out of shape at the same time as the statue was moving.
> 
> Check out the other issue on "[Sketchup...!](https://github.com/SASDigitalHumanitiesTraining/3D/issues/13)" as some of these questions have been discussed there

The answer from the other thread seems to be that it will stay blue in the free version. I'm also wondering if the file size from Metashape is too large. There seems to be a bit of a lag, after which all sorts of errors appear on the screen. I've had the statue disappear into walls, walls starting to rotate, all sorts... So far I've spent 4 hours, not yet got to the cornice

**Comment by gabrielbodard** [comment]
It is *really* fiddly. Again, try editing the statue far away from the rest of the model, and move it over when it's ready. Also reducing the number of vertices (“decimating”) in Metashape before you import may help, as Alicia explained.

An object is blue when it is selected (all the vertices in the "component" — collection of objects that are locked together — are highlighted). If it has no texture, then it will look grey or transparent when you zoom in close and it's not selected. As far as I understand, importing an **.obj** may well lose the texture in the free version, but objects I've imported from the Warehouse seem fine, so maybe they're **.dae** (i.e. Collada) and that brings the texture with them? Will experiment…
