### ISSUE TITLE
Importing object into 3D model

### ISSUE THREAD

**Issue by HansvanWees** [SASDigitalHumanitiesTraining/3D#2]
Skipped straight ahead to the SketchUp modelling exercise - sorry.  Among my problems was that in the final bit of the exercise, importing a 3D object, I can just about get the object into the scene, but it won't stay fixed in place or even in size.  When I move it on top of anything else, it becomes vastly larger and more or less swallows up the other object...  I should say that despite trying to follow instructions and getting only the free basic version, I seem to have somehow ended up with a 30-day trial 'Pro' version all the same.

**Comment by HansvanWees** [comment]
Oh, and the quality of the imported image is terrible - the original is far from perfect but when imported it appears either as a bright blue mesh or, if you zoom in a lot, like a dark blurry mesh. Is that as good as it gets or am I missing a trick?

**Comment by gabrielbodard** [comment]
Hi Hans,

I think you drop the object by clicking once at (or near) the point where you want it—you can then move it. After you have clicked once, the object should still be selected, so you can then resize it (using the scale button); always drag from one of the corners of the object, to be sure of scaling it uniformly—zoom in first if necessary.

![Scale button](https://user-images.githubusercontent.com/612845/124489287-b7a1a380-dda8-11eb-9af3-177d2be9741f.png)

Likewise you can then move the object once it's the right size, and hopefully it is still selected if you haven't clicked elsewhere on the screen…

**Comment by gabrielbodard** [comment]
Re quality: if you change back to the "pointer" button and click off the object, the blue mesh should disappear. I guess what you see after that is the quality of the object that was uploaded.

**Comment by HansvanWees** [comment]
Thanks, Gabby - I'll give that another try later.
Hans

**Comment by gabrielbodard** [comment]
For the record, this is very fiddly, so don't feel bad if it takes you a few tries to figure it out. Remember that ctrl+z / undo is your friend.
