### ISSUE TITLE
How to export the photogrammetry model

### ISSUE THREAD

**Issue by AnnaRuhland** [SASDigitalHumanitiesTraining/3D#3]
I just finished my photogrammetry exercise and wanted to save/ export it, but unfortunately the video tutorial stopped right before the last step, which is this:
![Screenshot how to export](https://user-images.githubusercontent.com/86601418/124501235-7669bd80-ddc1-11eb-9c97-13aa381c3d22.JPG)
What exactly must then be done? Probably Alicia can answer best.
(Sorry if this is a too detailed question, but I am just inescure about doing anything wrong and then losing all the work).
Thanks in advance!

**Comment by gabrielbodard** [comment]
Assigning this to Alicia as she's used Metashape more recently than I have.

But just to add: you should _also_ save your progress as a Metashape project regularly as you go along, so even if you make a mistake when exporting (or the software crashes, which can happen sometimes) you don't lose everything.

**Comment by Al-scw** [comment]
I would recommend keeping the default settings as is. So everything that is checked there is good, including exporting as a jpeg

**Comment by AnnaRuhland** [comment]
Thanks to both of you!

**Comment by gabrielbodard** [comment]
I'd like to keep this issue open, as it is a questions others may also find useful. Thanks!
