### ISSUE TITLE
uploading on sketchfab

### ISSUE THREAD

**Issue by HansvanWees** [SASDigitalHumanitiesTraining/3D#4]
This question may be answered in this afternoon's guest lecture, so may be premature to ask, but I tried uploading my (very poor) 3D image on Sketchfab and making it freely accessible, but despite clicking the 'Free' button, it comes up as an image I own, for which others would have to pay (as if!), and which uses up my allocation for the rest of the month.  I've tried it twice, with the same result each time.  (Though how can I use up my allocation twice is not unclear...)
This is the link to the model, if anyone wants to have a look:
https://sketchfab.com/3d-models/aryballos-collada-edb2ac8765714193919b20a469991391

**Comment by HansvanWees** [comment]
Ah, never mind - third time lucky I think, so I've deleted the earlier version and there should now be a freely accessible version on Sketchfab at https://sketchfab.com/3d-models/aryballos-fake-edb2ac8765714193919b20a469991391

**Comment by gabrielbodard** [comment]
That's odd. As far as I can see the "make it downloadable" feature is set as in the screenshot below:

![Screen Shot 2021-07-06 at 12 19 21](https://user-images.githubusercontent.com/612845/124591809-a4e4a880-de54-11eb-9b42-874975300674.png)

(But I've just done that—with a low res, incomplete file that is horrible!—and it also doesn't seem to be downloadable. Maybe it needs to be vetted before the download button appears, or something?)

**Comment by gabrielbodard** [comment]
Actually, a clue: when I went in to edit model settings, to check that it was downloadable, it said "Your model is being prepared for downloading. This may take a few minutes." So I guess leave it an hour, and hopefully it will fix itself…

**Comment by gabrielbodard** [comment]
And yes, I now see the "Download" button on your Aryballos, Hans!

**Comment by HansvanWees** [comment]
Great - glad it worked.  I see that I have a whole series of messages from Sketchfab which seem to imply that it did actually work once before and that I was too hasty to conclude that it had not...  So the simple answer is that, if you accidentally upload without clicking the button 'Free', you can go to 'Edit Settings', click 'Free' and 'Save', and then exercise a bit of patience in case it takes a while to implement the change.  Lesson learnt!

________________________________

**Comment by gabrielbodard** [comment]
Yes… :) Even if you do select "Free" the first time, it takes a few minutes to activate the download (they have to convert the files into Sketchfab's internal download format, as well as making your original file downloadable).
