### ISSUE TITLE
What kind(s) of images are usable?

### ISSUE THREAD

**Issue by HansvanWees** [SASDigitalHumanitiesTraining/3D#5]
A different kind of question: could a set of old B/W photos in .jpeg format in principle be converted into a 3D model?  The reason I'm asking is that several hundred photos of the 1894 Troy excavations are freely available from the DAI's Arachne programme, including many that give multiple views of the same bit of the excavation.  These are not systematically taken to provide comprehensive cover, so there is a lot of detail of some bits but only sketchy coverage of others.  For one bit I'm interested in there are probably about 30 pictures from different angles, but e.g. none from above or from the back.  Is this worth a try or doomed to fail?

**Comment by gabrielbodard** [comment]
As we discussed in the call earlier today, this is probably worth trying, but it will be tricky (at the very least!). The fact that the rear of the monument is missing from the photos will obviously mean a hole in the model, but that's not fatal—many models only include the surface·s of interest. It may be that it won't work at all, but once you have a bit more experience in photogrammetry you may have some ideas for tricks that will improve things a bit.

From seeing the image of the site in question, I suspect that you're going have more joy with modelling than scanning, as we said (or you could combine the two).

**Comment by gabrielbodard** [comment]
This may be a start on understanding how "markers" work in Metashape
https://agisoft.freshdesk.com/support/solutions/articles/31000148855 (but it's presumably a slightly different process to add them to existing images…
