### ISSUE TITLE
Struggling with getting my photos into Agisoft

### ISSUE THREAD

**Issue by chattyplatty** [SASDigitalHumanitiesTraining/3D#6]
Hi! I've been trying all morning and am really struggling with the first part of this. I have taken the photos on my i-phone and have transferred them to my computer and saved them in a file on my desktop. But, when I try to load them into Agisoft, they won't load. When I go through the steps on Agisoft, the image icons of my photos are greyed out and when I select them all, the 'open' button at the bottom does nothing. I have made sure that I have 'all formats' selected but nothing will import. Conversely, when I have tried not having 'all formats' selected and have selected 'all files' the photos come into colour and allow me to click on 'open'. But then Agisoft tells me it can't 'load photos'. I'm rather at a loss with what to do... Can you help?

**Comment by chattyplatty** [comment]
Ha! I *think* I might have fixed my own issue - it was something to do with a new feature on i-phones to save space and keep quality. Photos are defaulted on my phone to save as .heic

**Comment by gabrielbodard** [comment]
Yes, that's a known problem, and horrible. If you managed to solve it (i.e. get your photos to export from phone or iPhoto as .jpg or similar) would you mind quickly explaining how or linking to a help page here? I think this will be useful for a lot of people.

**Comment by chattyplatty** [comment]
Sure - here is the link that I found which was useful:

[https://backlightblog.com/iphone-heic-to-jpg](url)
