### ISSUE TITLE
Issue with uploading my model to Sketchfab

### ISSUE THREAD

**Issue by GeorgePrew** [SASDigitalHumanitiesTraining/3D#7]
Hi! Very sorry if I am missing something obvious, but I have been having trouble uploading my 3D model to Sketchfab - After exporting my edited model from Meshmixer as a .obj file and uploading it to Sketchfab along with the .mtl, .jpg, and .png files also produced by Meshmixer with the .obj file, the model still appears untextured on Sketchfab. I think the issue might be that the jpeg provided by Meshmixer when I exported the model as a .obj file still includes texture for areas of the object which I had deleted in Meshmixer, so it may not be able to map it to the .obj file? Is there a way to sort this out?

**Comment by gabrielbodard** [comment]
Tricky to troubleshoot this without being in front of the computer; the [Sketchfab forums](https://forum.sketchfab.com/search?q=texture%20obj%20category%3A7) may have some clues. Otherwise, perhaps try exporting your model in a format that includes textures in a single file, such as Collada or gLTF, and see if that works better.

(Anyone else tried uploading a model as multiple files, and can share whether it worked or not?)

**Comment by Al-scw** [comment]
You can also try only uploading either the jpg produced on metashape, or the png from meshmixer, but not both.

**Comment by GeorgePrew** [comment]
Thank you very much for the advice! As it turned out, saving as Collada worked, especially when exporting directly from Metashape. I am still having some trouble with Meshmixer and will continue to experiment, but I have now been able to upload some of my models (both successful and interestingly-failed) [here](https://sketchfab.com/GeorgePrew)!

**Comment by nebulousflynn** [comment]
Hi @GeorgePrew, Tom from Sketchfab here.

For future reference, I'd recommend:

1. Using the built in Metashape to Sketchfab uploader (File Menu > Upload Data... > Sketchfab)
2. Open the 3D Settings for each model and [upload and assign textures manually](https://help.sketchfab.com/hc/en-us/articles/202600873-Materials-and-Textures#textures)

**Comment by GeorgePrew** [comment]
Hi @nebulousflynn - That is extremely helpful, thank you! I shall give it a try tomorrow morning. Thanks also again for your fascinating talk on Tuesday.

**Comment by LindaStoessel** [comment]
I also habe trouble uploading my models to Sketchfab. I have managed to upload one [model](https://sketchfab.com/3d-models/greek-terracotta-figurine-cd71f1fa6f9c41ee81fb20788fd95af0) but two others I created are too big (Sketchfab says max. 50 MB or upgrade to Pro/Premium). Even as a zip-file both are too large (105 MB). I probably lack basic skills here, but is there anything else I can change about the files to compress them?

**Comment by Al-scw** [comment]
> I also habe trouble uploading my models to Sketchfab. I have managed to upload one [model](https://sketchfab.com/3d-models/greek-terracotta-figurine-cd71f1fa6f9c41ee81fb20788fd95af0) but two others I created are too big (Sketchfab says max. 50 MB or upgrade to Pro/Premium). Even as a zip-file both are too large (105 MB). I probably lack basic skills here, but is there anything else I can change about the files to compress them?

You can demicate (reduce the polygons) on Meshmixer, which will bring the file size down. (It may also reduce the overall quality of your model though). There's a tutorial on how do to this here : https://www.google.com/search?q=meshmixer+decimate&oq=meshmixer+demicate&aqs=chrome.1.69i57j0i13.27683j0j4&client=ms-android-xiaomi-rev2&sourceid=chrome-mobile&ie=UTF-8#kpvalbx=_SfLnYLiUJYP1sAfHpK24Cg6

**Comment by LindaStoessel** [comment]
Thank you @Al-scw! It worked and I managed to upload it [here](https://sketchfab.com/3d-models/portal-of-a-church-dd7444e494f04ce59dc9595ddae78300)
