### ISSUE TITLE
Model uploaded on Sketchfab

### ISSUE THREAD

**Issue by Lynchtosca** [SASDigitalHumanitiesTraining/3D#9]
Dear All,
I didn't have time to take new pictures today, so today I've worked with some of the pictures generously shared by Dan Pett (thanks for the link, @gabrielbodard!). It has taken a while, but here is [the model that I've just uploaded to Sketchfab](https://skfb.ly/oozBx) – the visualisation could be better, I think, but it's a start! 
Tosca

**Comment by Lynchtosca** [comment]
I'm not sure how I can assign people to this post, but at least I managed to tag Gabby ;-)

**Comment by Al-scw** [comment]
Wonderful work Tosca!

**Comment by gabrielbodard** [comment]
That does look great, @Lynchtosca, thanks for sharing! (And good practice to credit Dan for the photos in Sketchfab.)

**Comment by nebulousflynn** [comment]
Hi @Lynchtosca, Tom from Sketchfab here, your model looks good! Some tips you might like to try:

- It looks like this model might not be oriented correctly in the scene space - it's easy to adjust and fine tune model orientation in 3D Settings: https://help.sketchfab.com/hc/en-us/articles/203064198-Scene#general 
- This would look great with a ground shadow: https://help.sketchfab.com/hc/en-us/articles/203557159-Lighting#ground-shadows
- Some real-time Ambient Occlusion might look great on this model: https://help.sketchfab.com/hc/en-us/articles/115000728943-Post-Processing-Filters#ssao 
- Try adding a 'sharpness' filter, this will help bring out a lot  more detail: https://help.sketchfab.com/hc/en-us/articles/115000728943-Post-Processing-Filters#sharp

**Comment by Lynchtosca** [comment]
Thank you so much for these suggestions and very helpful links, @nebulousflynn! 
I'll look into these options in the coming days, it's all very new to me—but also very interesting.
Tosca
